# Generated by Django 5.0.6 on 2024-07-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("title", models.CharField(max_length=255, verbose_name="Rental title")),
                ("description", models.TextField(blank=True, verbose_name="Rental description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is rental active")),
            ],
            options={
                "verbose_name": "Rental",
                "verbose_name_plural": "Rentals",
            },
        ),
    ]
